micronaut:
  application:
    name: manager-srv-delivery

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2Dialect

jpa:
  default:
    entity-scan:
      packages: 'com.manager.api.domain.entities'