micronaut:
  application:
    name: manager-srv-delivery

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: username
    password: password
    dialect: H2

jpa:
  default:
    properties:
        hibernate:
            hbm2ddl:
              auto: update